import assert from 'node:assert/strict';
import { runPlatformChecks } from './platform-browser.mjs';
import { runCameraChecks } from './camera-browser.mjs';
import { runLossChecks } from './loss-browser.mjs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { mkdir } from 'node:fs/promises';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const browser = await chromium.launch({ headless: true });
const out = fileURLToPath(new URL('../test-results/', import.meta.url));
await mkdir(out, { recursive: true });
const errors = [];
const page = await browser.newPage({ viewport: { width: 1280, height: 1000 } });
page.on('pageerror', e => errors.push(e.message));
await page.route('https://www.youtube.com/game_api/v1', r => r.fulfill({ contentType: 'text/javascript', body: '' }));
await page.goto('http://127.0.0.1:8080');
await page.locator('#home').waitFor({ state: 'visible' });
await page.screenshot({ path: out + 'desktop-menu.png', fullPage: true });
await page.click('#new-game');
assert.equal(await page.locator('.cell').count(), 81);
await page.locator('.cell').nth(40).click();
assert.ok(await page.locator('.cell.open').count() > 1);
const openCount = await page.locator('.cell.open').count();
await page.waitForTimeout(1100);
assert.notEqual(await page.locator('#time').textContent(), '00:00');
await page.click('#pause');
const pausedTime = await page.locator('#time').textContent();
await page.waitForTimeout(1150);
assert.equal(await page.locator('#time').textContent(), pausedTime);
await page.click('#resume');
await page.screenshot({ path: out + 'desktop-game.png', fullPage: true });
await page.click('#menu');
await page.reload();
await page.click('#continue');
assert.equal(await page.locator('.cell.open').count(), openCount);
const closed = page.locator('.cell:not(.open):not(.flagged)').first();
await closed.click({ button: 'right' });
assert.equal(await page.locator('.cell.flagged').count(), 1);
await page.locator('.cell.flagged').press('f');
assert.equal(await page.locator('.cell.flagged').count(), 0);
await page.click('#flag-mode');
await closed.click();
assert.equal(await page.locator('.cell.flagged').count(), 1);
const beforeResize = await page.locator('#board').innerHTML();
for (const [width, height] of [[360,1280],[360,840],[360,640],[600,800],[700,700],[800,600],[1280,720],[1260,540],[1600,450],[240,850]]) {
  await page.setViewportSize({ width, height });
  await page.waitForTimeout(30);
  assert.equal(await page.locator('#board').innerHTML(), beforeResize);
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `page overflow ${width}x${height}`);
  assert.ok(await page.locator('.cell').first().evaluate(el => parseFloat(getComputedStyle(el).width) >= 32));
}
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: out + 'mobile-game.png', fullPage: true });
await page.click('#menu');
await page.screenshot({ path: out + 'mobile-menu.png', fullPage: true });
await page.click('[data-level=expert]');
await page.click('#new-game'); await page.click('#confirm-new');
assert.equal(await page.locator('.cell').count(), 480);
// Native Chromium touch sequence, including long-press pointer capture.
const cdp = await page.context().newCDPSession(page);
const cellRect = await page.locator('.cell').nth(3).boundingBox();
const touch = { x: cellRect.x + cellRect.width / 2, y: cellRect.y + cellRect.height / 2, id: 1 };
await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [touch] });
await page.waitForTimeout(480);
await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
assert.equal(await page.locator('.cell.flagged').count(), 1);
assert.equal(await page.locator('.cell.open').count(), 0);
// Zoom in before panning: a fitted board correctly remains centered.
for (let i=0;i<5;i++) await page.click('#zoom-in');
const rect = await page.locator('#board-viewport').boundingBox();
const beforePan = await page.locator('#board').evaluate(el => el.style.transform);
await page.mouse.move(rect.x + rect.width / 2, rect.y + rect.height / 2); await page.mouse.down();
await page.mouse.move(rect.x + rect.width / 2 - 90, rect.y + rect.height / 2, { steps: 5 }); await page.mouse.up();
assert.notEqual(await page.locator('#board').evaluate(el => el.style.transform), beforePan);
assert.equal(await page.locator('.cell.open').count(), 0);
await page.click('#fit');
await page.locator('.cell').first().focus(); await page.keyboard.press('ArrowRight');
assert.equal(await page.evaluate(() => document.activeElement.dataset.index), '1');
await page.keyboard.press('Enter');
assert.ok(await page.locator('.cell.open').count() > 0);
// Recover layout after a zero-size container without replacing the board.
await page.locator('#board-viewport').evaluate(el => { el.style.width='0px'; el.style.height='0px'; });
await page.waitForTimeout(30);
await page.locator('#board-viewport').evaluate(el => { el.style.width=''; el.style.height=''; });
await page.waitForTimeout(30);
assert.ok(await page.locator('.cell').first().evaluate(el => Number.isFinite(el.getBoundingClientRect().width)));
assert.equal(errors.length, 0, errors.join('\n'));
console.log('PASS: menu, gameplay, mouse, right-click, keyboard, flag mode, long press, drag, save/continue, pause, 10 viewport ratios, zero-size recovery.');
await runPlatformChecks(browser, out);
await runCameraChecks(browser, out);
await runLossChecks(browser, out);
await browser.close();
